### ISSUE TITLE
Web scraping on Liquipedia

### ISSUE THREAD

**Issue by FO-nTTaX** [leonardodiegues/liquipedia#1]
Please do not webscrape Liquipedia. It takes a ton of resources on our server, and it will get yourself IP banned in no time. You can use the API with the mentioned API-limits of your blog post about this, or you will get banned. 
Thank you for your consideration.

**Comment by leonardodiegues** [comment]
No problem Alex. I will not web scrap Liquipedia anymore and I will
advertise others so they don't web scrap it either.

I was only interested in doing a sort of web scraping excercise and I did
not imagine how costful it would be to your servers. I apologize.

Sincerely yours,

Leonardo.


Em 18 de jan de 2018 10:09, "Alex Winkler" <notifications@github.com>
escreveu:

Please do not webscrape Liquipedia. It takes a ton of resources on our
server, and it will get yourself IP banned in no time. You can use the API
with the mentioned API-limits of your blog post about this, or you will get
banned.
Thank you for your consideration.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/leonardodiegues/liquipedia/issues/1>, or mute the thread

**Comment by FO-nTTaX** [comment]
If you ever want to do anything with Liquipedia, you are of course welcome to just use the API :)
Thanks a bunch!
